config/routes.rb
Rails.application.routes.draw do
  #rotas
  resources :students
  resources :courses
  resources :classrooms

  #rota inicial
  root "classrooms#index"
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  #Relacionamento cada matrícula pode ter um estudante e um curso
  belongs_to :students
  belongs_to :courses
end

app/models/courses.rb
class Courses < ActiveRecord::Base
  #Validações, garantindo que os campos estejam preenchidos, caso não a mensagem é salva no error e emitida como mensagem de erro para o usuário
  validates_presence_of :name, message: "não pode ficar em branco"
  validates_presence_of :description, message: "não pode ficar em branco"
  validates_presence_of :status, message: "não pode ficar em branco"

  # Relacionamento, um curso pode ter muitas matrículas.
  has_many :classroom
end

app/models/students.rb
class Students < ActiveRecord::Base
  #Validações, garantindo que os campos estejam preenchidos, caso não a mensagem é salva no error e emitida como mensagem de erro para o usuário
  validates_presence_of :name, message: "não pode estar em branco"
  validates_presence_of :register_number, message: "(RG) não pode ficar em branco"
  validates_presence_of :status, message: "não pode ser indefinido"

  #Relacionamento, um estudante pode fazer várias matriculas.
  has_many :classroom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
=begin
  Antes dos métodos show, edit e update ele verifica o método find_classrooms
  em nenhum dos controllers eu coloquei o método da ação destroy já que isso retira informações do banco
  e como ele possui um status eu preferi deixar ativando e inativando status.
=end

  before_action :find_classrooms, only: [:show, :edit, :update]

  def index
    @classrooms = Classroom.all.order('created_at DESC')
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)

    #se a matricula for salva ele redireciona para a tela show, caso contrário ela renderiza a tela new com os erros na tela
    if @classroom.save
      redirect_to @classroom
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  private
  #os params que são esperados e salvos
  def classroom_params
    params.require(:classroom).permit(:students_id, :courses_id, :entry_at)
  end

  #busca uma matrícula expecifica
  def find_classrooms
    @classroom = Classroom.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
=begin
  Antes dos métodos show, edit e update ele verifica o método find_course.
  em nenhum dos controllers eu coloquei o método da ação destroy, já que isso retira informações do banco
  e como ele possui um status eu preferi deixar ativando e inativando status.
=end

  before_action :find_course, only: [:show, :edit, :update]

  def index
    @courses = Courses.all.order('created_at DESC')
  end

  def new
    @course = Courses.new
  end

  #salva se der certo ele redireciona para mostrar as informações salvas, se não ele reinderiza a tela new
  def create
    @course = Courses.new(course_params)

    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end

  #salva se der certo ele redireciona para mostrar as informações salvas, se não ele reinderiza a tela edit
  def update
    if @course.update(course_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
  end

  private
  #os params que são esperados e salvos
  def course_params
    params.require(:courses).permit(:name, :description, :status)
  end

  #busca um curso expecifico
  def find_course
    @course = Courses.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
=begin
  Antes dos métodos show, edit e update ele verifica o método find_classrooms
  em nenhum dos controllers eu coloquei o método da ação destroy já que isso retira informações do banco
  e como ele possui um status eu preferi deixar ativando e inativando status.
=end
  before_action :find_student, only: [:show, :edit, :update]

  def index
    @students = Students.all.order('created_at DESC')
  end

  def new
    @student = Students.new
  end

  #se a matricula for salva ele redireciona para a tela show, caso contrário ela renderiza a tela new com os erros na tela
  def create
    @student = Students.new(students_params)

    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  #salva se der certo ele redireciona para mostrar as informações salvas, se não ele reinderiza a tela edit
  def update
    if @student.update(students_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
  end

  private
  #os params que são esperados e salvos
  def students_params
    params.require(:students).permit(:name, :register_number, :status)
  end

  #busca um curso expecifico
  def find_student
    @student = Students.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<!-- Formulário que nos selects busca através do collect todos os cursos, tras o name e o id, coloca o campo em branco pelo atributo
include_blank e utiliza a class form-control do bootstrap -->
<%= f.label :courses_id, "Curso" %>
<%= select("classroom", "courses_id", Courses.all.collect {|course| [ course.name, course.id ] }, {include_blank: true}, { class: "form-control"}) %>

<%= f.label :students_id, "Aluno" %>
<%= select("classroom", "students_id", Students.all.collect {|student| [ student.name, student.id ] }, {include_blank: true}, { class: "form-control"}) %>

<!-- Para salvar o momento do save foi criado um campo oculto solicitando o horário no momento, apesar de ter usado o :entry_at achei que
poderia ter usado o created_at e economizado um campo na tabela, mas como estava no modelo de relacionamento criei o :entry_at mesmo assim -->
<%= f.hidden_field :entry_at, value: Time.now %>
<br>
<div class="form-group">
  <%= f.submit "Enviar", class: "btn btn-primary" %>
</div>

app/views/classrooms/edit.html.erb
<h2>Alterar Matrícula</h2>

<!-- Utiliza um render para reutilizar o form em mais de uma página -->
<%= form_for @classroom, url: classrooms_path(@classroom), html: { method: :post } do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/classrooms/index.html.erb
<h2>Matriculas</h2>
<!-- Tabela estilizada com bootstrap trazando o nome do estudante, curso matriculado e a data da matricula, foi utilizado o strftime para
estilizar o horário -->
  <table class="table table-striped">
    <tr><td>Matricula</td><td>Aluno</td><td>Curso</td><td>Matriculado</td><td>Opções</td></tr>
      <% @classrooms.each do |classroom| %>
        <tr>
          <td><%= classroom.id %></td>
          <td><%= classroom.students.name %></td>
          <td><%= classroom.courses.name %></td>
          <td><%= classroom.entry_at.strftime("%d/%m/%Y - %H:%M:%S") %></td>
          <td>
            <%= link_to "Visualizar", classroom, class: "btn-sm btn-default" %> | <%= link_to "Editar", edit_classroom_path(classroom), class: "btn-sm btn-default" %>
          </td>
        </tr>
      <% end %>
  </table>

  <br>
  <%= link_to "Nova Matrícula", new_classroom_path, class: "btn btn-primary" %>
</div>

app/views/classrooms/new.html.erb
<h2>Nova Matricula</h2>

<!-- Utiliza um render para reutilizar o form em mais de uma página -->
<%= form_for @classroom, url: classrooms_path, html: { method: :post } do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/classrooms/show.html.erb
<h3 class="title">Dados do Aluno</h3>
<!-- Mostra os dados do aluno já salvo no banco -->
<table class="table table-striped">
  <tbody>
    <tr><td>Nome do Aluno: </td><td><%= @classroom.students.name %></td></tr>
    <tr><td>Número de Registro</td><td><%= @classroom.students.register_number %></td></tr>
    <tr><td>Status do Aluno</td><td><%= @classroom.students.status %></td></tr>
  </tbody>
</table>

<!-- Mostra os dados do curso que ele foi matriculado -->
<h3 class="title">Curso Matriculado</h3>
<table class="table table-striped">
  <tbody>
    <tr><td>Nome do Curso: </td><td><%= @classroom.courses.name %></td></tr>
    <tr><td>Descrição do Curso: </td><td><%= @classroom.courses.description %></td></tr>
    <tr><td>Data de Matrícula: </td><td><%= @classroom.entry_at.strftime("%d/%m/%Y - %H:%M:%S") %></td></tr>
  </tbody>
</table>

<%= link_to 'Voltar', root_path %>

app/views/courses/_form.html.erb
<!-- Verifica se tem alguma mensagem de erro para imprimir na tela -->
<% if @course.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@course.errors.count, "erro") %> impossibilitaram a continuação do processo:</h2>

    <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- Formulário utilizando a classe form-control do bootstrap para estilizar o form -->
<div class="form-group">
  <%= f.label :name, "Nome do Curso" %><br>
  <%= f.text_field :name, class: "form-control", placeholder: "Nome do curso sem abreviações" %>
</div>

<div class="form-group">
  <%= f.label :description, "Descrição do Curso" %><br>
  <%= f.text_field :description, class: "form-control", placeholder: "Descrição do curso" %>
</div>

<div class="form-group">
  <%= f.label :status, "Status" %>
  <%= f.select :status, [['Ativo', '1'], ['Inativo', '0']], { include_blank: true }, { class: "form-control"}  %>
</div>
<br>
<div class="form-group">
  <%= f.submit "Enviar", class: "btn btn-primary" %>
</div>

app/views/courses/edit.html.erb
<h2>Editar Informações do Curso</h2>

<!-- Utiliza um render para reutilizar o form em mais de uma página -->
<%= form_for @course, url: course_path(@course), html: { method: :put } do |f| %>
  <%= render 'form', f: f %>
<% end %>

<!-- Link que retorna para a lista completa dos cursos -->
<%= link_to 'Voltar', courses_path %>

app/views/courses/index.html.erb
<h2>Cursos Cadastrados</h2>
<!-- Tabela estilizada com bootstrap trazando o nome, descrição e status do curso -->
<table class="table table-striped">
  <tr><td>Cursos</td><td>Descrição</td><td>Status</td><td>Opções</td></tr>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td>
          <% if course.status == 1 %>
            Ativo
          <% else %>
            Inativo
          <% end %>
        </td>
        <td>
          <%= link_to "Visualizar", course, class: "btn-sm btn-default" %> | <%= link_to "Editar", edit_course_path(course), class: "btn-sm btn-default" %>
        </td>
      </tr>
    <% end %>
</table>

<br>
<!-- Link leva ao formulário para criar um novo curso -->
<%= link_to "Novo Curso", new_course_path, class: "btn btn-primary" %>

app/views/courses/new.html.erb
<h2>Novo Curso</h2>

<!-- Utiliza um render para reutilizar o form em mais de uma página -->
<%= form_for @course, url: courses_path, html: { method: :post } do |f| %>
  <%= render 'form', f: f %>
<% end %>

<!-- Link que retorna para a lista completa dos cursos -->
<%= link_to 'Voltar', courses_path %>

app/views/courses/show.html.erb
<h3 class="title">Dados do Curso</h3>
<!-- Mostra os dados do curso já salvo no banco -->
<table class="table table-striped">
  <tbody>
    <tr><td>Nome do Curso: </td><td><%= @course.name %></td></tr>
    <tr><td>Descrição do Curso:</td><td><%= @course.description %></td></tr>
    <tr><td>Status do Curso:</td>
      <td>
        <% if @course.status == 1 %>
          Ativo
        <% else %>
          Inativo
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'Voltar', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Utilização das classes navbar e suas derivadas no header, para ter a barra fixa no topo -->
<header class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo" class="navbar-brand"><%= link_to "REPENSE", root_path %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Lista de Estudantes", students_path %></li>
          <li><%= link_to "Lista de Cursos", courses_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

<div id="main_content "class="container">
  <div id="content" class="col-md-9 center-block">
    <%= yield %>
  </div>
</div>


</body>
</html>

app/views/students/_form.html.erb
<!-- Verifica se tem alguma mensagem de erro para imprimir na tela -->
<% if @student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@student.errors.count, "erro") %> impossibilitaram a continuação do processo:</h2>

    <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- Formulário utilizando a classe form-control do bootstrap para estilizar o form -->
<div class="form-group">
  <%= f.label :name, "Nome" %><br>
  <%= f.text_field :name, class: "form-control", placeholder: "Nome Completo" %>
</div>

<div class="form-group">
  <%= f.label :register_number, "Número de Registro" %><br>
  <%= f.text_field :register_number, class: "form-control", placeholder: "Número do RG" %>
</div>

<div class="form-group">
  <%= f.label :status, "Status" %>
  <%= f.select :status, [['Ativo', '1'], ['Inativo', '0']], { include_blank: true }, { class: "form-control"}  %>
</div>
<br>

<div class="form-group">
  <%= f.submit  "Enviar", class: "btn btn-primary"%>
</div>

app/views/students/edit.html.erb
<h2>Editar Dados do Estudante</h2>

<!-- Utiliza um render para reutilizar o form em mais de uma página -->s
<%= form_for @student, url: student_path(@student), html: { method: :put } do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Voltar', students_path %>

app/views/students/index.html.erb
<h2>Lista de Estudantes</h2>
<!-- Tabela estilizada com bootstrap trazendo o nome, número de registro e status do curso -->
<table class="table table-striped">
  <tr><td>Nome</td><td>Número de Registro</td><td>Status</td><td>Opções</td></tr>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td>
          <% if student.status == 1 %>
            Ativo
          <% else %>
            Inativo
          <% end %>
        </td>
        <td>
          <%= link_to "Visualizar", student, class: "btn-sm btn-default" %> | <%= link_to "Editar", edit_student_path(student), class: "btn-sm btn-default" %>
        </td>
      </tr>
    <% end %>
</table>

<br>
<%= link_to "Novo Estudante", new_student_path, class: "btn btn-primary" %>

app/views/students/new.html.erb
<h2>Novo Estudante</h2>

<!-- Utiliza um render para reutilizar o form em mais de uma página -->
<%= form_for @student, url: students_path, html: { method: :post } do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Voltar', students_path %>

app/views/students/show.html.erb
<h3 class="title">Dados do Aluno</h3>
<!-- Mostra os dados do aluno já salvo no banco -->
<table class="table table-striped">
  <tbody>
    <tr><td>Nome do Aluno: </td><td><%= @student.name %></td></tr>
    <tr><td>Número de Registro</td><td><%= @student.register_number %></td></tr>
    <tr><td>Status do Aluno</td>
      <td>
        <% if @student.status == 1 %>
          Status: Ativo
        <% else %>
          Status: Inativo
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<!-- Mostra os cursos que o aluno já está matriculado -->
<h3>Cursos Matrículado</h3>
<table class="table table-striped">
  <tr><td>Curso</td><td>Descrição</td><td>Data e Hora</td></tr>
  <% Classroom.all.each do |classroom| %>
  </tr>
    <% if classroom.students_id == @student.id %>
      <td><%= classroom.courses.name %></td><td><%= classroom.courses.description %></td><td><%= classroom.entry_at.strftime("%d/%m/%Y - %H:%M:%S") %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<%= link_to 'Voltar', students_path %>